### PR TITLE
Refactor engine-specific handling code to use classes

### PR DESCRIPTION
**Pull request by JAORMX**
This is a small refactor that moves the if statements for
engine-specific cases in the parsing code to use classes instead.

### CODE REVIEW

**Comment by JAORMX** [comment]
@wrabcak huh... CI seems broken. Anybody looking at this?

```
Failed to start: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/libpod-218412/global/images/fedora-31-libpod-6268069335007232'. The referenced image resource cannot be found.
```

**Comment by wrabcak** [comment]
Hi @cevich, 
Can you please check the CI? 

THanks,
Lukas.

**Comment by cevich** [comment]
> Can you please check the CI?

Yes, I see the problem...

**Comment by cevich** [comment]
...rebase onto #64 and it will solve the surface-problem.  There's a more subtle problem that's the root-cause, I opened an issue and willl look at it in the next few days.

**Comment by wrabcak** [comment]
LGTM. THanks.

**Pull request merged**
