### PR TITLE
Add initial support for Cirrus-CI testing

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@wrabcak it just occurred to me that running tests inside a container may not fly as we're dealing with SELinux stuffs here.  Is there a way to make this work or do we need a VM?

If so, it's probably not a show-stopper, it will just take me some time to organize all the requirements to make that happen.

Let me know.

**Comment by cevich** [comment]
clarification:  This is for integration testing.  If you like, I can port the current Travis tests over into Cirrus-CI as well (it is quite a bit faster) but in a future PR.

**Comment by wrabcak** [comment]
> @wrabcak it just occurred to me that running tests inside a container may not fly as we're dealing with SELinux stuffs here. Is there a way to make this work or do we need a VM?
> 

Exactly, SELinux is not inside the container, so we need Fedora/RHEL VM for proper testing of udica.

> If so, it's probably not a show-stopper, it will just take me some time to organize all the requirements to make that happen.
> 
> Let me know.

Thanks,
Lukas.

**Comment by cevich** [comment]
I can swing Fedora pretty easily, but RHEL is a huge amount of work.  It can be done, but it's quite painful. Okay, I'll go down the Fedora VM path first.  Setup-wise it's quite involved, maybe half a day of fast typing if I'm lucky and don't forget some detail :smile:

**Comment by wrabcak** [comment]
@cevich , For now it's enough to have CI on Fedora VMs.

Thanks for your contribution. :) 
Lukas.

**Comment by cevich** [comment]
Small progress:

* Created a google project to house the VMs.

Next step: secure $$$ for ^^^

**Comment by cevich** [comment]
Got head-nod for $$$ to wire in Cirrus-CI + VMs to validate this.

**Comment by cevich** [comment]
Still working on making things official.

**Comment by cevich** [comment]
Okay, we're supported in running CI in google cloud.  Next step is for me to start wiring things together with Cirrus CI so it can manage the VMs.  I've got a number of tasks ahead of this one, but will avoid starting an new ones.  Should be able to make progress on this one starting early next week.

**Comment by wrabcak** [comment]
Hi @cevich , 

Thank you for your time and help, no pressure, this could wait. :) 

Lukas

**Comment by cevich** [comment]
@wrabcak @rhatdan PTAL this is ready to go.

Lukas - I added a script `hack/get_ci_vm.sh` similar to what we use in other projects, it will give you access to a VM for debugging, configured nearly exactly as in CI.  However, since you're outside the US, it will be very slow (network-wise) unless I share some tricks.  Write me an e-mail so I have your redhat.com address, can grant you GCE access + explain how to get fast networking to the VMs.

**Comment by wrabcak** [comment]
Amazing! Thanks for PR!  Merging. 

Yep, I'll send you e-mail. 

Thanks,
Lukas.

**Pull request merged**
